classDiagram
    class mcu["MCU"] {
        <<component>>
        +role: controller
    }
    class sensor["Temperature Sensor"] {
        <<component>>
        +interface: I2C
    }
    class radio["Radio"] {
        <<component>>
        +interface: SPI
    }
    mcu -- sensor : I2C
    mcu -- radio : SPI
