@startuml
class "MCU" as mcu <<component>> {
  +role: controller
}
class "Temperature Sensor" as sensor <<component>> {
  +interface: I2C
}
class "Radio" as radio <<component>> {
  +interface: SPI
}
mcu -- sensor : I2C
mcu -- radio : SPI
@enduml
